@token=abc

POST http://localhost/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "test1",
    "username": "tester1",
    "email": "test1@mail.com",
    "password": "password",
    "confirm_password": "password"
}
###
POST http://localhost/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "test2@mail.com",
    "password": "password"
}
###
POST http://localhost/api/logout
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json
###