@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2OTIzMDQzOCwiZXhwIjoxNzY5MjMwNzM4LCJuYmYiOjE3NjkyMzA0Mzh9.Tchrnj5S7LpQwSnlEHXz-sx2TjlSSzxBT5b5QIz5pRE

POST http://localhost:3000/api/tasks/1/comments
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "testing"
}
###
PUT http://localhost:3000/api/comments/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "Testing"
}
###
DELETE http://localhost:3000/api/comments/1
Authorization: Bearer {{token}}
Accept: application/json