@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2OTI0NTA3OCwiZXhwIjoxNzY5MjQ1Mzc4LCJuYmYiOjE3NjkyNDUwNzh9.puGkV8oMmLZwSB4kliIQhn79OX1AiDCk1JrjF5pZI6o

GET http://localhost:3000/api/profile
Authorization: Bearer {{token}}
###
PUT http://localhost:3000/api/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}
###