@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2ODkxNjg4NSwiZXhwIjoxNzY4OTE3MTg1LCJuYmYiOjE3Njg5MTY4ODV9.SjZugztCyHeJawibjSIoLMf7twbtjnnWOIFdZk2Lc7o

GET http://localhost/api/profile
Authorization: Bearer {{token}}
###
PUT http://localhost/api/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}
###