@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2MDYwNDgwNywiZXhwIjoxNzYwNjA4NDA3LCJuYmYiOjE3NjA2MDQ4MDd9.389-r4ofGMqngmjI_GQtY2jjPSdR_a5_Hd5iqILH_HU

GET http://localhost/api/profile
Authorization: Bearer {{token}}
###
PUT http://localhost/api/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}
###