@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2MjI1MDc4OSwiZXhwIjoxNzYyMjU0Mzg5LCJuYmYiOjE3NjIyNTA3ODl9.jCwJwebdQwN70oE2uQ-yM_jz5Im9ASmwaVojtfMnfVQ

POST http://localhost/api/projects/1/members
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "members": [
        {
            "id": 2,
            "role": "member"
        }
    ]
}
###

DELETE http://localhost/api/projects/1/members/2
Authorization: Bearer {{token}}
Accept: application/json