@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2OTQ5OTU3NSwiZXhwIjoxNzY5NDk5ODc1LCJuYmYiOjE3Njk0OTk1NzV9.Nu-ERX6HKACu-w3BAPqnCAe4YpBbWc5DibuFQGlFpOY

POST http://localhost/api/projects/1/members
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "members": [
        {
            "id": 2,
            "role": "member"
        },
        {
            "id": 3,
            "role": "viewer"
        }
    ]
}
###

DELETE http://localhost/api/projects/1/members/3
Authorization: Bearer {{token}}
Accept: application/json