@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2MjI1MDc4OSwiZXhwIjoxNzYyMjU0Mzg5LCJuYmYiOjE3NjIyNTA3ODl9.jCwJwebdQwN70oE2uQ-yM_jz5Im9ASmwaVojtfMnfVQ

GET http://localhost/api/projects
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost/api/projects
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "another testing",
    "status": "active"
}
###
GET http://localhost/api/projects/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost/api/projects/2
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    # "name": "Testing 1"
    "start_date": "2025-09-10"
}
###
DELETE http://localhost/api/projects/4
Authorization: Bearer {{token}}
Accept: application/json