@token=abc

POST http://localhost/api/projects/{id}/members
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "members": [
        {
            "id": 3,
            "role": "viewer"
        },
        {
            "id": 2,
            "role": "owner"
        },
        {
            "id": 1,
            "role": "member"
        }
    ]
}
###

DELETE http://localhost/api/projects/1/members/2
Authorization: Bearer {{token}}
Accept: application/json