@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2MTc5NTQyOSwiZXhwIjoxNzYxNzk5MDI5LCJuYmYiOjE3NjE3OTU0Mjl9.HAxXQO10DTXTNzMaqogBA5TBhYCZ_4QVHlYukVnJESo

GET http://localhost/api/projects?search=active&sort=id_asc
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost/api/projects
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "another testing",
    "status": "active"
}
###
GET http://localhost/api/projects/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost/api/projects/2
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    # "name": "Testing 1"
    "start_date": "2025-09-10"
}
###
DELETE http://localhost/api/projects/4
Authorization: Bearer {{token}}
Accept: application/json