@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2OTQ5OTU3NSwiZXhwIjoxNzY5NDk5ODc1LCJuYmYiOjE3Njk0OTk1NzV9.Nu-ERX6HKACu-w3BAPqnCAe4YpBbWc5DibuFQGlFpOY

GET http://localhost:3000/api/projects
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost:3000/api/projects
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "another testing",
    "status": "active"
}
###
GET http://localhost:3000/api/projects/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost:3000/api/projects/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "Testing 1",
    "start_date": "2025-11-10"
}
###
DELETE http://localhost:3000/api/projects/2
Authorization: Bearer {{token}}
Accept: application/json