@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2OTQ5OTU3NSwiZXhwIjoxNzY5NDk5ODc1LCJuYmYiOjE3Njk0OTk1NzV9.Nu-ERX6HKACu-w3BAPqnCAe4YpBbWc5DibuFQGlFpOY

GET http://localhost/api/projects/1/tasks
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost/api/projects/1/tasks
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "title": "testing",
    "assigned_to": 1
}
###
GET http://localhost/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "title": "Testing",
    "status": "complete"
}
###
DELETE http://localhost/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json