@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2OTI0NTA3OCwiZXhwIjoxNzY5MjQ1Mzc4LCJuYmYiOjE3NjkyNDUwNzh9.puGkV8oMmLZwSB4kliIQhn79OX1AiDCk1JrjF5pZI6o

GET http://localhost:3000/api/projects/1/tasks
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost:3000/api/projects/1/tasks
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "title": "testing",
    "assigned_to": 1
}
###
GET http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "title": "Testing",
    "status": "complete"
}
###
DELETE http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json