@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2OTIzMDQzOCwiZXhwIjoxNzY5MjMwNzM4LCJuYmYiOjE3NjkyMzA0Mzh9.Tchrnj5S7LpQwSnlEHXz-sx2TjlSSzxBT5b5QIz5pRE

GET http://localhost:3000/api/projects/1/tasks
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost:3000/api/projects/1/tasks
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "title": "testing",
    "assigned_to": 1
}
###
GET http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "title": "Testing",
    "status": "complete"
}
###
DELETE http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}
Accept: application/json