@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2MTkyODEzOSwiZXhwIjoxNzYxOTMxNzM5LCJuYmYiOjE3NjE5MjgxMzl9._rd8YIxEgtVSh1AIy7mhPNG_MF3Lj3MOQ0rcJo8_Y_M

GET http://localhost/api/teams
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost/api/teams
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "testing A",
    "description": "Testing A team"
}
###
GET http://localhost/api/teams/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost/api/teams/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Testing A",
    "description": "A testing A team"
}
###
DELETE http://localhost/api/teams/2
Authorization: Bearer {{token}}