@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2MjE0NjI5NSwiZXhwIjoxNzYyMTQ5ODk1LCJuYmYiOjE3NjIxNDYyOTV9.zgrCwDIWUHZJl5PlpzhTI3LpEeXfUuvFFGSuxvdPZTQ

GET http://localhost/api/teams
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost/api/teams
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "testing A",
    "description": "Testing A team"
}
###
GET http://localhost/api/teams/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost/api/teams/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "Testing A",
    "description": "A testing A team"
}
###
DELETE http://localhost/api/teams/2
Authorization: Bearer {{token}}
Accept: application/json