@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlhdCI6MTc2MTEwNjI0NCwiZXhwIjoxNzYxMTA5ODQ0LCJuYmYiOjE3NjExMDYyNDR9.mQ1MCI3YV7Wjfk5WQQOWIOV-zhN4JosJNFjcjaqQWyk

GET http://localhost/api/teams
Authorization: Bearer {{token}}
Accept: application/json
###
POST http://localhost/api/teams
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "testing b",
    "description": "A testing b team"
}
###
GET http://localhost/api/teams/1
Authorization: Bearer {{token}}
Accept: application/json
###
PUT http://localhost/api/teams/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Testing A",
    "description": "A testing A team"
}
###
DELETE http://localhost/api/teams/2
Authorization: Bearer {{token}}