name: Test
on:
  pull_request:
    branches: ['main']

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build docker images based on docker compose file
        run: docker compose -f docker-compose-dev.yaml up -d

      - name: Run a test command in laravel_app container
        run: docker compose -f docker-compose-dev.yaml exec -T laravel_app bash -c "
            composer install &&
            cp .env.example .env &&
            php artisan key:generate &&
            echo \"JWT_SECRET=\$(openssl rand -base64 64)\" >> .env &&
            php artisan test"

      - name: Clean up and remove the container
        if: always()
        run: docker compose -f docker-compose-dev.yaml down -v